version: '3.8'

services:
  web:
    image: ghcr.io/beta-dev64/betabevsurvey:latest
    container_name: flask_backend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./dangote_execution.db:/app/dangote_execution.db
      - ./static/uploads:/app/static/uploads
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production